### ISSUE TITLE
Is it possible to define which laravel docs should be searched?

### ISSUE THREAD

**Issue by KuenzelIT** [brpaz/ulauncher-docsearch#6]
Hi,

is it possible to disable some versions of the laravel docs? Sometimes I get to the Laravel 5 docs, which we don't use anymore.

Thank you for this extension!

**Comment by iksaku** [comment]
In my case, it sends me to v8 docs, which search term is sending you to 5.x?

**Comment by KuenzelIT** [comment]
There are search results for a lot of version, e.g. if I use "laradocs queue" and take the fourth result, then I get to:
https://laravel.com/docs/5.1/queues#introduction

I had a search term where I got to Laravel 5 docs with the first search result, but I don't remember the term. I just feel like it would be nice to disable or enable versions, maybe in a config file? Then there wouldn't be as many search results but only for the versions that are enabled.

**Comment by iksaku** [comment]
Yeah, many results come. Maybe a way to either show the "config version" or enable/disable versions from a config. Not sure if algolia tells which version is a result linking to.

**Comment by brpaz** [comment]
From what I have seen on the Laravel website, the version is specified on the request done to algolia, in the facet filters property:

```
facetFilters	"[\"version:6.x\"]"
```

I think this logic is specific to the Laravel documentation, The concept of versions is interesting and could be nice to add to this extension. The issue is other projects could implement it in a different way. so I don't see a way of adding a "generic" configuration that would work for every documentation.

I would prefer to have a separate extension.

There is a [Laravel Docs](https://github.com/mabasic/ulauncher-laravel) extension for ulauncher. Maybe it would be better for your use cases
